spring:
  application:
    name: expense-manager

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId}] %-5level %logger - %msg%n"

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html

