spring.application.name=expensemanager

#db connection properties
spring.datasource.url=jdbc:mysql://localhost:3306/expense_manager
spring.datasource.username=newuser
spring.datasource.password=Pass@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true